services:
  dev:
    container_name: ai-assistants-dev
    image: alexfariakof/jail-container:latest
    build:
      context: ../AI-Assistants
      dockerfile: ../.devcontainer/Dockerfile
    volumes:
      - ../helpers-repo:/helpers-repo
    ports:
      - "9877:9876"
      - "5001:5000"
      - "4201:4200"
    command: /bin/bash  -l
    shm_size: "2g"
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "1"
